name: Build

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build .

      - uses: actions/upload-artifact@v4
        with:
          name: hcpi
          path: result/bin/hpci-exe
